# Based on: https://github.com/kartoza/docker-postgis/blob/develop/docker-compose.yml

# docker-compose build
version: '3.9'

volumes:
  culvert-vision-mvp-pg-dev-data:


services:
  postgis-dev:
    image: kartoza/postgis:15-3.3
    volumes:
      - culvert-vision-mvp-pg-dev-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=culvert_vision_mvp
      - POSTGRES_USER=dev
      - POSTGRES_PASS=dev
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the five specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
      - RUN_AS_ROOT=true
    ports:
      # Avoid exposing on 5432 as the port may be already be occupied on the dev host
      - "15432:5432"
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=$POSTGRES_PASS pg_isready -h 127.0.0.1 -U $POSTGRES_USER -d $POSTGRES_DB"
