name: culvert-vision-mvp
channels:
  - conda-forge
dependencies:
  # Python environment
  - python=3.10.*
  - pip
  - poetry=1.6.*


  # Geospatial
  - gdal=3.7.1
  - libgdal-arrow-parquet=3.7.1 # for gdal's GeoParquet driver
  # gRPC is a dependency of dagster-webserver
  # It is pinned for compatibility with libgdal-arrow-parquet
  - grpcio=1.56.2 
